### ISSUE TITLE
你好，有个问题请教一下

### ISSUE THREAD

**Issue by 0x000-0** [80998062/YukDaily#1]
最近看了一些文章，想用RxJava 来实现一个RxBus，然后 发现你也在使用EventBus和RXjava，（我EventBus接触比较少），你选择 EventBus而没有用RxJava来实现RxBus，想必你是有所见解的，请指教。

只看了这个，感觉说得挺模糊的
http://stackoverflow.com/questions/35685577/what-is-the-difference-between-eventbus-and-rxjava

**Comment by Sinyuk7** [comment]
用Rxjava自己来实现事件总线还是蛮多坑的(效率&功能)
EventBus有[greenrobot](http://greenrobot.org/)在维护,放心用就好了...
虽然RxBus最简单的实现应该没几行代码吧...但是EventBus也不大,除非强迫症为了保持和Rxjava的代码一致性,没理由不用EventBus而去踩坑吧..

**Comment by 0x000-0** [comment]
好吧，看来我是有点强迫症了，没关系，反正闲着也是闲着 😂
